### ISSUE TITLE
Different ResNet references in train.py and guess.py

### ISSUE THREAD

**Issue by sassalley** [lizadaly/guesso#2]
Hi Liza,

Firstly, fantastic article. Thanks for taking the time to document your process.

I just wanted to suggest that in the README, you refer to using ResNet152. In `train.py` I think the script is using `model = models.resnet50(pretrained=True)`. 

In `guess.py` the script uses `model = models.resnet152(num_classes=1).cuda()`. I think for it to work the version of ResNet needs to be the same in each one (please forgive me if this is not true).

I tried your methodology on some other imagery and trained it with `model = models.resnet50(pretrained=True)` and needed to change the reference in `guess.py` to `model = models.resnet50(num_classes=1).cuda()`.

**Comment by lizadaly** [comment]
You're right, plus the links to the pretrained models were wrong anyway. I standardized on the 152 model. Thanks for the issue and I hope your experiments worked out!
